
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  host: 192.168.1.14
  port: 5432
  database: allinf_dev
  username: dev
  password: allinf

test:
  <<: *default
  host: 192.168.1.14
  port: 5432
  database: allinf_test
  username: dev
  password: allinf

production:
  <<: *default
  host: 192.168.1.14
  port: 5432
  database: allinf_prod
  username: dev
  password: allinf
