
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  host: 146.83.194.142
  port: 5432
  database: bmosso_bd
  username: bmosso
  password: bmosso1479

test:
  <<: *default
  host: 146.83.194.142
  port: 5432
  database: bmosso_bd
  username: bmosso
  password: bmosso1479

production:
  <<: *default
  host: 146.83.194.142
  port: 5432
  database: bmosso_bd
  username: bmosso
  password: bmosso1479
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  host: <%= ENV['TEST_DATABASE_HOST'] %>
  port: <%= ENV['TEST_DATABASE_PORT'] %>
  database: <%= ENV['TEST_DATABASE_NAME'] %>
  username: <%= ENV['TEST_DATABASE_USERNAME'] %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] %>

production:
  <<: *default
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  port: <%= ENV['PRODUCTION_DATABASE_PORT'] %>
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
