
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  host: pgsql.face.ubiobio.cl
  port: 5432
  database: bmosso_bd
  username: bmosso
  password: bmosso1479

test:
  <<: *default
  host: pgsql.face.ubiobio.cl
  port: 5432
  database: bmosso_bd
  username: bmosso
  password: bmosso1479

production:
  <<: *default
  host: pgsql.face.ubiobio.cl
  port: 5432
  database: bmosso_bd
  username: bmosso
  password: bmosso1479
